# Student Performance Prediction Usingf Logistic Regression

A beginner machine learning Project that predictswhether a student will pass or fail based on study hours, attendance, and assignment score.

## Project Objective
The goal of this project is to build a classification model that predict a student (pass or fail) using:
- Hours studied
- Attendance
- assignment score
This project is part of my laerning journey in python, Data Analysis, and machine Learning.

## using pandas to create a Dataset of students

In [31]:
# First, we import our libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
 accuracy_score,
 classification_report,
 confusion_matrix
)

## Creating Dataset

In [13]:
data = {
    'Student': ['Esther', 'Halimah', 'Rahmat', 'Salamat', 'Carina', 
                'Jemilah', 'Lola', 'Racheal', 'Funmi', 'Tomi',
                'Zainab', 'Shogbade', 'Loveth', 'Nofisat', 'Arafat',
                'Adeola', 'Abiola', 'Rhoda', 'Hannah'],
    'Hours_Studied': [2, 4, 6, 1, 5, 3, 7, 8, 2, 6, 4, 1, 5, 3, 7, 9, 4, 7, 3],
    'Attendance': [60, 75, 85, 50, 80, 65, 90, 95, 55, 78, 70, 45, 82, 60, 88, 66, None, 78, 76 ],
    'Assignment_Score': [45, None, 72, 40, 68, 55, 82, 88, 48, 70, 62, 35, 75, 50, 80, 50, 58, 48, 83],
    'Result': ['Fail', 'Pass', 'Pass', 'Fail', 'Pass',
              'Fail', 'Pass', 'Pass', 'Fail', 'Pass',
              'Pass', 'Fail', 'Pass', 'Fail', 'Pass',
              'Pass', 'Pass', 'Pass', 'Fail']
}

In [15]:
data = pd.DataFrame(data)

In [16]:
data

     Student  Hours_Studied  Attendance  Assignment_Score Result
0     Esther              2        60.0              45.0   Fail
1    Halimah              4        75.0               NaN   Pass
2     Rahmat              6        85.0              72.0   Pass
3    Salamat              1        50.0              40.0   Fail
4     Carina              5        80.0              68.0   Pass
5    Jemilah              3        65.0              55.0   Fail
6       Lola              7        90.0              82.0   Pass
7    Racheal              8        95.0              88.0   Pass
8      Funmi              2        55.0              48.0   Fail
9       Tomi              6        78.0              70.0   Pass
10    Zainab              4        70.0              62.0   Pass
11  Shogbade              1        45.0              35.0   Fail
12    Loveth              5        82.0              75.0   Pass
13   Nofisat              3        60.0              50.0   Fail
14    Arafat              7        88.0              80.0   Pass
15    Adeola              9        66.0              50.0   Pass
16    Abiola              4         NaN              58.0   Pass
17     Rhoda              7        78.0              48.0   Pass
18    Hannah              3        76.0              83.0   Fail

In [14]:
df.to_csv('student_dataset.csv', index=False)

In [15]:
df.head()

   Student  Hours_Studied  Attendance  Assignment_Score Result
0   Esther              2        60.0              45.0   Fail
1  Halimah              4        75.0               NaN   Pass
2   Rahmat              6        85.0              72.0   Pass
3  Salamat              1        50.0              40.0   Fail
4   Carina              5        80.0              68.0   Pass

In [ ]:
# Data preparation
The dataset will be inspected for missing values and basic information about the columns. And missing values will be handled using "SimpleImputer" with the mean strategy.

In [16]:
#Checking and identifying missing data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student           19 non-null     str
 1   Hours_Studied     19 non-null     int64
 2   Attendance        18 non-null     float64
 3   Assignment_Score  18 non-null     float64
 4   Result            19 non-null     str
dtypes: float64(2), int64(1), str(2)
memory usage: 1.1 KB

In [17]:
df.describe()

       Hours_Studied  Attendance  Assignment_Score
count      19.000000   18.000000         18.000000
mean        4.578947   72.111111         61.611111
std         2.364454   14.179060         16.186919
min         1.000000   45.000000         35.000000
25%         3.000000   61.250000         48.500000
50%         4.000000   75.500000         60.000000
75%         6.500000   81.500000         74.250000
max         9.000000   95.000000         88.000000

In [18]:
## identifying missing data
df.isnull().sum()

Student             0
Hours_Studied       0
Attendance          1
Assignment_Score    1
Result              0
dtype: int64

In [17]:
from sklearn.impute import SimpleImputer

In [18]:
imputer = SimpleImputer(strategy='mean')

In [19]:
data[['Attendance', 'Assignment_Score']] = imputer.fit_transform(
    data[['Attendance', 'Assignment_Score']]
)

In [20]:
print(data.shape)

(19, 5)

In [21]:
print(data[['Attendance', 'Assignment_Score']].shape)

(19, 2)

In [22]:
data[['Attendance', 'Assignment_Score']].isnull().sum()

Attendance          0
Assignment_Score    0
dtype: int64

In [55]:
for column in data:
    print(column, len(data[column]))

Student 19
Hours_Studied 19
Attendance 19
Assignment_Score 19
Result 19

In [35]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student           19 non-null     str
 1   Hours_Studied     19 non-null     int64
 2   Attendance        19 non-null     float64
 3   Assignment_Score  19 non-null     float64
 4   Result            19 non-null     str
dtypes: float64(2), int64(1), str(2)
memory usage: 1.1 KB

### now we want to choose our features 

and for this Dataset we will not be using Student column for prediction because it's just an identifier

In [27]:
## Select features and Target
features = data[['Hours_Studied', 'Attendance', 'Assignment_Score']]
target = data['Result']

In [28]:
print(features.shape)
print(target.shape)

(19, 3)
(19,)

In [30]:
print(type(data))
print(data)

<class 'pandas.DataFrame'>
     Student  Hours_Studied  Attendance  Assignment_Score Result
0     Esther              2   60.000000         45.000000   Fail
1    Halimah              4   75.000000         61.611111   Pass
2     Rahmat              6   85.000000         72.000000   Pass
3    Salamat              1   50.000000         40.000000   Fail
4     Carina              5   80.000000         68.000000   Pass
5    Jemilah              3   65.000000         55.000000   Fail
6       Lola              7   90.000000         82.000000   Pass
7    Racheal              8   95.000000         88.000000   Pass
8      Funmi              2   55.000000         48.000000   Fail
9       Tomi              6   78.000000         70.000000   Pass
10    Zainab              4   70.000000         62.000000   Pass
11  Shogbade              1   45.000000         35.000000   Fail
12    Loveth              5   82.000000         75.000000   Pass
13   Nofisat              3   60.000000         50.000000   Fail
14    Arafat              7   88.000000         80.000000   Pass
15    Adeola              9   66.000000         50.000000   Pass
16    Abiola              4   72.111111         58.000000   Pass
17     Rhoda              7   78.000000         48.000000   Pass
18    Hannah              3   76.000000         83.000000   Fail

### Splitting the Data

In [32]:
#since i have imported all the libraries from the begining we can train and test
# from sklearn.model_selection import train_test_split, GridSearchCV

In [33]:
features_train, features_test, target_train, target_test = train_test_split(
    features,
    target,
    test_size=0.2, #means 20% of the data will be used  for testing
    random_state=42 #to get same split each the code is run
)

In [34]:
#Checking the shapes
print(features_train.shape)
print(features_test.shape)
print(target_train.shape)
print(target_test.shape)

(15, 3)
(4, 3)
(15,)
(4,)

## Choosing a model
since the target variable contains two categories (pass and fail), this is a classification problem i use Logistic Regression as the machine learning algorithm.

In [35]:
from sklearn.linear_model import LinearRe

## Creating a model

In [37]:
model = LinearRegression()

In [38]:
## Now let's train our model

### while trying to Train the model i have this error because LinearRegression expects a number to predict and i need to decide what my result represents since my target is Pass/Fail, so i think this is a classification problem and am changing the model from LinearRegression to LogisticRegression

In [40]:
#since i have import from the begining
model = LogisticRegression()

In [41]:
model.fit(features_train, target_train)

LogisticRegression()

In [42]:
#Now i want to make prediction
predictions = model.predict(features_test)

In [43]:
print(predictions)

['Fail' 'Pass' 'Fail' 'Pass']

In [44]:
### let's check the actual results
print(target_test.values)

<ArrowStringArray>
['Fail', 'Fail', 'Fail', 'Pass']
Length: 4, dtype: str

In [46]:
comparison = pd.DataFrame({
    "Actual": target_test.values,
    "Predicted": predictions
})

print(comparison)

  Actual Predicted
0   Fail      Fail
1   Fail      Pass
2   Fail      Fail
3   Pass      Pass

In [48]:
accuracy = accuracy_score(target_test, predictions)

print(accuracy)

0.75

In [51]:
print(f"Accuracy: {accuracy * 100:.0f}%")

Accuracy: 75%

## Confusion Matrix

In [52]:
cm = confusion_matrix(target_test, predictions)

print(cm)

[[2 1]
 [0 1]]

In [53]:
print(classification_report(target_test, predictions))

              precision    recall  f1-score   support

        Fail       1.00      0.67      0.80         3
        Pass       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4

## Model Evaluation

The model correctly predicted 3 out of 4 observations in the test set, giving an accuracy of 75%.

Because the dataset contains only 19 observations and the test set contains only 4 observations, the accuracy should be interpreted cautiously.

### Confusion Matrix

The confusion matrix was:

[[2 1]
 [0 1]]

This shows that the model correctly classified 3 of the 4 test observations and incorrectly classified 1.

A classification report was also generated to examine precision, recall, F1-score, and support.

## Key Learning Outcomes

Through this project, I practiced:

- Creating and exploring a dataset
- Detecting missing values
- Handling missing values with SimpleImputer
- Selecting features and target variables
- Splitting data into training and testing sets
- Building a Logistic Regression model
- Making predictions
- Evaluating a classification model
- Understanding accuracy and confusion matrices
- Using GitHub to document and share my work

## Future Improvements

- Use a larger dataset
- Explore more classification models
- Compare model performance
- Add data visualizations
- Explore additional evaluation metrics